title: JonahPlusPlus
description: >- 
  JonahPlusPlus's Development Blog
url: jonahplusplus.dev
baseurl: ""
twitter_username: 
github_username: JonahPlusPlus
favicon: /assets/images/common/monogram-128.png
favicon_type: image/svg+xml

plugins:
  - jekyll-feed

